---
- name: install dependency
  apt:
    name: "{{item}}"
    state: present
    update_cache: yes
  loop:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg-agent
    - software-properties-common

- name: Add signing key
  ansible.builtin.apt_key:
    url: "https://download.docker.com/linux/{{ ansible_os_family | lower }}/gpg"
    state: present

- name: Get DEB architecture
  shell: dpkg --print-architecture
  register: deb_architecture

- name: Set default distribution values
  set_fact:
    distribution: "{{ ansible_distribution }}"
    distribution_release: "{{ ansible_distribution_release }}"
  when: distribution is not defined and distribution_release is not defined

- name: Add repository into sources list
  ansible.builtin.apt_repository:
    repo: "deb [arch={{ deb_architecture.stdout }}] https://download.docker.com/linux/{{ distribution | lower }} {{ distribution_release }} stable"
    state: present
    filename: docker

- name: Install Docker
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose
      - docker-compose-plugin
    state: latest
    update_cache: true

- name: Start and enable docker service
  ansible.builtin.service:
    name: docker
    enabled: yes
    state: started